version: '3.8'
services:
  titan-bot:
    build: .
    container_name: titan-bot
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./auth_info:/app/auth_info
      - ./data:/app/data
    environment:
      - OWNER_NUMBER=${OWNER_NUMBER}
      - BOT_NAME=${BOT_NAME}
      - PREFIX=${PREFIX}
      - MODE=${MODE}
      - AUTO_JOIN_LINK=${AUTO_JOIN_LINK}
