services:
  - type: web
    name: titan-whatsapp-bot
    runtime: node
    buildCommand: npm install --no-audit --no-fund
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: OWNER_NUMBER
        sync: false
        placeholder: "e.g. 2348081234567"
        description: "Your Phone Number (Include Country Code, but NO '+' or spaces)"
      - key: BOT_NAME
        value: "TITAN"
        description: "What do you want to call your robot?"
      - key: PREFIX
        value: "."
        description: "The character to start commands (Example: .)"
      - key: OPENROUTER_KEY
        description: "AI Intelligence Key (Optional - Only if you have your own)"
